REGISTRY_SERVER1: 192.168.2.118
REGISTRY_SERVER1_PORT: 8761
REGISTRY_SERVER2: 127.0.0.1
REGISTRY_SERVER2_PORT: 8762
REGISTRY_SERVER_USERNAME: user
REGISTRY_SERVER_PASSWORD: password
ADMIN_SERVER: 127.0.0.1
ADMIN_SERVER_PORT: 8082
ADMIN_SERVER_USERNAME: user
ADMIN_SERVER_PASSWORD: password
RABBITMQ_SERVER: 192.168.2.118
RABBITMQ_SERVER_PORT: 5672
RABBITMQ_SERVER_USERNAME: admin
RABBITMQ_SERVER_PASSWORD: 123456
ZIPKIN_SERVER: 127.0.0.1
ZIPKIN_SERVER_PORT: 9411
REDIS_SERVER: 192.168.2.118
REDIS_SERVER_PORT: 6379
REDIS_SERVER_USERNAME: admin
REDIS_SERVER_PASSWORD:
ROCKETMQ_SERVER: 127.0.0.1
ROCKETMQ_SERVER_PORT: 9876
OUTERGATEWAYNAME: ifmis-gateway-outer-xj
MICROSERVICEGATEWAYNAME: ifmis-gateway-microservice-xj
#ORCLDATASOURCE: jdbc:oracle:thin:@localhost:1521:orcl
#ORCLUSER: C##EFMIS430000
ORCLDATASOURCE: jdbc:oracle:thin:@192.168.2.211:1521/orcl
ORCLUSER: ifmis_34
CONFIG_SERVER: 192.168.2.118
CONFIG_SERVER_PORT: 8880
CONFIG_SERVER_USERNAME: user
CONFIG_SERVER_PASSWORD: password

security:
  loginpage: http://${GATEWAY_SERVER:192.168.2.118}:${GATEWAY_SERVER_PORT:8080}/busportal/login.page
  ignoring:
    antpatterns: '/sys/**,/buscommon/distribute.hess,/rest/**,/buscommon/**'
  fliter:
    hunan: true
  authorization:
    server:
      address: 192.168.2.150:8015

synchronous:
  data:
    ca:
      province: 430000
      year: 2020
      po: ctjCaClientPO
      server:
        address: 192.168.2.244:6662
    dic:
      province: 430000
      year: 2020
      server:
        address: 192.168.2.245:80
